### ISSUE TITLE
Doesn't seem to work on iPhone

### ISSUE THREAD

**Issue by robx** [mpizenberg/demo-elm-image-annotation#1]
Not quite sure where/if to file this, but in response to the reddit thread at https://www.reddit.com/r/elm/comments/7gksya/pointer_mousetouchpointer_events_community/, I've been trying to get https://github.com/mpizenberg/elm-pointer-events to work for touch input.

Everything works fine in "responsive design mode" with simulated touch events, but I just can't get things to work when I use an actual iPhone. After a bit of debugging https://github.com/mpizenberg/elm-pep, I thought to try whether the demo at http://elm-image-annotation.pizenberg.fr actually works, and it turns out that I don't seem to be able to draw (or event select tools) using Safari or Firefox (which should use elm-pep) or even Chrome (which shouldn't?).

I'd be happy to help dig into this further, I'm a bit lost right now. If you'd prefer to take this to elm-pointer-events or elm-pep, let me know.

**Comment by mpizenberg** [comment]
Hum thanks for that, not having any apple device to test things is really a PITA for me sometimes. If I'm right, the issue with iOS devices is that even firefox and chrome are forced to use apple webkit as a JS engine (I'm not sure but I think so) which would explain that they behave consistently with regard to each other i.e. not working XD.

I would really appreciate any apple-related help! The elm-pointer-events package seems to be working fine according to my tests so I'd bet that this issue is related to the polyfill elm-pep.

I will come back to you as soon as I have some time, quite busy this weekend (changing appartement), thanks again!

**Comment by robx** [comment]
Closing in favour of https://github.com/mpizenberg/elm-pep/issues/4
